In [28]:
import pandas as pd
import numpy as np

hp_data = pd.read_csv('./house_price_data.csv')
hp_updated = hp_data.copy()

In [29]:
hp_updated = hp_updated.drop(['Unnamed: 0'], axis=1)
hp_updated

,Property Name,Price,House Type,Area in sq ft,No. of Bedrooms,No. of Bathrooms,No. of Receptions,Location,City/County,Postal Code
0,Queens Road,1675000,House,2716,5,5,5,Wimbledon,London,SW19 8NY
1,Seward Street,650000,Flat / Apartment,814,2,2,2,Clerkenwell,London,EC1V 3PA
2,Hotham Road,735000,Flat / Apartment,761,2,2,2,Putney,London,SW15 1QL
3,Festing Road,1765000,House,1986,4,4,4,Putney,London,SW15 1LP
4,Spencer Walk,675000,Flat / Apartment,700,2,2,2,Putney,London,SW15 1PL
...,...,...,...,...,...,...,...,...,...,...
3475,One Lillie Square,3350000,New development,1410,3,3,3,NaN,Lillie Square,SW6 1UE
3476,St. James's Street,5275000,Flat / Apartment,1749,3,3,3,St James's,London,SW1A 1JT
3477,Ingram Avenue,5995000,House,4435,6,6,6,Hampstead Garden Suburb,London,NW11 6TG
3478,Cork Street,6300000,New development,1506,3,3,3,Mayfair,London,W1S 3AR
3479,Courtenay Avenue,8650000,House,5395,6,6,6,Highgate,London,N6 4LP

In [30]:
hp_updated = hp_updated.rename({'Area in sq ft':'Area (sq ft)', 'No. of Bedrooms': 'Bedrooms', 'No. of Bathrooms': 'Bathrooms', 'No. of Receptions': 'Receptions'}, axis=1)

In [31]:
hp_updated['Location'] = hp_updated['Location'].fillna("Unknown")

In [32]:
hp_updated.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3480 entries, 0 to 3479
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Property Name  3480 non-null   object
 1   Price          3480 non-null   int64
 2   House Type     3480 non-null   object
 3   Area (sq ft)   3480 non-null   int64
 4   Bedrooms       3480 non-null   int64
 5   Bathrooms      3480 non-null   int64
 6   Receptions     3480 non-null   int64
 7   Location       3480 non-null   object
 8   City/County    3480 non-null   object
 9   Postal Code    3480 non-null   object
dtypes: int64(5), object(5)
memory usage: 272.0+ KB

In [33]:
hp_updated['Price per sqft'] = (hp_updated['Price'] / hp_updated['Area (sq ft)'])

In [34]:
hp_updated

,Property Name,Price,House Type,Area (sq ft),Bedrooms,Bathrooms,Receptions,Location,City/County,Postal Code,Price per sqft
0,Queens Road,1675000,House,2716,5,5,5,Wimbledon,London,SW19 8NY,616.715758
1,Seward Street,650000,Flat / Apartment,814,2,2,2,Clerkenwell,London,EC1V 3PA,798.525799
2,Hotham Road,735000,Flat / Apartment,761,2,2,2,Putney,London,SW15 1QL,965.834428
3,Festing Road,1765000,House,1986,4,4,4,Putney,London,SW15 1LP,888.721047
4,Spencer Walk,675000,Flat / Apartment,700,2,2,2,Putney,London,SW15 1PL,964.285714
...,...,...,...,...,...,...,...,...,...,...,...
3475,One Lillie Square,3350000,New development,1410,3,3,3,Unknown,Lillie Square,SW6 1UE,2375.886525
3476,St. James's Street,5275000,Flat / Apartment,1749,3,3,3,St James's,London,SW1A 1JT,3016.009148
3477,Ingram Avenue,5995000,House,4435,6,6,6,Hampstead Garden Suburb,London,NW11 6TG,1351.747463
3478,Cork Street,6300000,New development,1506,3,3,3,Mayfair,London,W1S 3AR,4183.266932
3479,Courtenay Avenue,8650000,House,5395,6,6,6,Highgate,London,N6 4LP,1603.336423

In [35]:
hp_updated.to_csv('./updated_house_price_data.csv', index=False)

In [36]:
hp_updated.groupby(['Location']).agg({'Area (sq ft)':'mean', 'Price':'mean'})

                      Area (sq ft)         Price
Location
 161 Millbank               1293.0  2.900000e+06
 35 Salusbury Road           547.0  5.500000e+05
 352 Queenstown Road         722.0  8.250000e+05
 372 Queenstown Road         708.0  8.000000e+05
 50 Shad Thames             3701.0  8.950000e+06
...                            ...           ...
Winchester Road              669.0  6.700000e+05
Windsor Street               517.0  3.499500e+05
Woodberry Grove              795.0  5.950000e+05
Woodford Green              1909.0  1.052083e+06
Woodstock Road              1465.0  1.300000e+06

[657 rows x 2 columns]

In [37]:
hp_updated.groupby(['Bedrooms', 'Bathrooms', 'Receptions'])['Price'].median()

Bedrooms  Bathrooms  Receptions
0         0          0               367500.0
1         1          1               550000.0
2         2          2               810000.0
3         3          3              1300000.0
4         4          4              1585000.0
5         5          5              2100000.0
6         6          6              2950000.0
7         7          7              3500000.0
8         8          8              5250000.0
9         9          9             14750000.0
10        10         10             9975000.0
Name: Price, dtype: float64

In [38]:
hp_updated.groupby(['Bedrooms', 'Bathrooms', 'Receptions'])['Area (sq ft)'].median()

Bedrooms  Bathrooms  Receptions
0         0          0               362.5
1         1          1               560.5
2         2          2               880.0
3         3          3              1363.0
4         4          4              1909.0
5         5          5              2564.0
6         6          6              3783.0
7         7          7              4745.0
8         8          8              4197.0
9         9          9              9053.0
10        10         10            10100.0
Name: Area (sq ft), dtype: float64

In [39]:
hp_updated.groupby('Bedrooms')['Price per sqft'].median()

Bedrooms
0      961.270044
1      991.436175
2      944.828450
3      963.323054
4      828.500477
5      802.264748
6      791.662157
7      718.061674
8      986.951904
9     1448.904713
10     987.623762
Name: Price per sqft, dtype: float64

In [40]:
hp_updated[hp_updated['Bedrooms'] == 0]

,Property Name,Price,House Type,Area (sq ft),Bedrooms,Bathrooms,Receptions,Location,City/County,Postal Code,Price per sqft
154,Mare Street,260000,Studio,381,0,0,0,Hackney,London,E8 3RH,682.414698
350,Kersfield House,210000,Studio,328,0,0,0,Putney,London,SW15 3HJ,640.243902
393,Cumberland Terrace Mews,295000,Studio,344,0,0,0,Regent's Park,London,NW1 4HR,857.558140
436,Cautley Avenue,295000,Studio,277,0,0,0,Unknown,London,SW4 9HU,1064.981949
770,Montpellier Road,350000,Studio,425,0,0,0,Ealing,London,W5 2QS,823.529412
951,Vicarage Court,450000,Studio,410,0,0,0,Vicarage Gate,London,W8 4HF,1097.560976
1313,The Madison,573000,New development,429,0,0,0,199 To 207 Marsh Wall,London,E14 9YT,1335.664336
1345,Vandon Court,450000,Studio,332,0,0,0,Westminster,London,SW1H 9HE,1355.421687
1444,Eardley Crescent,385000,Studio,297,0,0,0,Unknown,London,SW5 9JT,1296.296296
1447,Wapping Lane,450000,Studio,680,0,0,0,Unknown,London,E1W 2RX,661.764706

In [41]:
hp_updated = hp_updated.drop(
    hp_updated[(hp_updated['Bathrooms'] == 0) & (hp_updated['Bedrooms'] == 0) & (hp_updated['Receptions'] == 0)].index
)

In [42]:
hp_updated = hp_updated.drop(
    hp_updated[
        (hp_updated['Bathrooms'] == 8) &
        (hp_updated['Bedrooms'] == 8) &
        (hp_updated['Receptions'] == 8)
    ].index
)
hp_updated = hp_updated.drop(
    hp_updated[
        (hp_updated['Bathrooms'] == 9) &
        (hp_updated['Bedrooms'] == 9) &
        (hp_updated['Receptions'] == 9)
    ].index
)
hp_updated = hp_updated.drop(
    hp_updated[
        (hp_updated['Bathrooms'] == 10) &
        (hp_updated['Bedrooms'] == 10) &
        (hp_updated['Receptions'] == 10)
    ].index
)

hp_updated['Bedrooms'].value_counts()

Bedrooms
2    1078
3     706
4     576
5     453
1     414
6     176
7      53
Name: count, dtype: int64

In [45]:
hp_updated.to_csv('./updated_house_price_data.csv', index=False)

In [46]:
hp_updated.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3456 entries, 0 to 3479
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Property Name   3456 non-null   object
 1   Price           3456 non-null   int64
 2   House Type      3456 non-null   object
 3   Area (sq ft)    3456 non-null   int64
 4   Bedrooms        3456 non-null   int64
 5   Bathrooms       3456 non-null   int64
 6   Receptions      3456 non-null   int64
 7   Location        3456 non-null   object
 8   City/County     3456 non-null   object
 9   Postal Code     3456 non-null   object
 10  Price per sqft  3456 non-null   float64
dtypes: float64(1), int64(5), object(5)
memory usage: 324.0+ KB